name: "⁉️ Custom Issue"
description: Create a ticket for new Custom Issue
title: "⁉️ [CUSTOM ISSUE] : " 
 
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please enter a detailed description of the incident
      placeholder: Explicit description of your incident...
        Mention the steps or situation to reproduce the issue
        Mention the environment details if any
    validations:
      required: true
  - type: input
    id: github-url
    attributes:
      label: "GitHub URL"
      description: Please enter your GitHub URL
      placeholder: ex. https://github.com/USERNAME
    validations:
      required: true  
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
