name: "💡 Feature Request"
description: Create a new ticket for requesting a new feature
title: "💡 [REQUEST] : "
labels: [
  "enhancement"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: Start of development
      placeholder: "month/day/year"
    validations:
      required: false
  - type: input
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs (if any)"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: |
        Clearly describe the desired feature or enhancement.
        * **Problem:** Briefly explain the issue or need.
        * **Solution:** Outline the proposed solution or feature.
        * **Benefits:** Highlight the advantages of implementing this feature.
      placeholder: "Problem: [Briefly describe the issue] | Solution: [Proposed feature] | Benefits: [Expected advantages]"
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of the feature 
      placeholder: Site examples where the feature gets used 
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the possible drawbacks/impacts this feature might introduce?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: What are the alternatives to this feature?
    validations:
      required: false
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved?
      placeholder: Identify any unresolved issues
    validations:
      required: false
  - type: textarea
    id: related_issues
    attributes:
      label: "Anything else?"
      description: |
        Links? References? Anything that will give us more insight into the feature and its advantage!
    validations:
      required: false
